version: '3.9'

services:
  cadastroclienteapi:
    image: ${DOCKER_REGISTRY-}cadastro-cliente
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqldb

  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Api#XP2023
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
